export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  SUBSCRIPTION_CHANGE = 'SUBSCRIPTION_CHANGE',
  ERROR = 'ERROR',
}
