export enum EmployeeType {
  WAITER = 'WAITER',
  PUMPIST = 'PUMPIST',
  CASHIER = 'CASHIER',
  CHEF = 'CHEF',
  MANAGER = 'MANAGER',
  BARISTA = 'BARISTA',
  BARTENDER = 'BARTENDER',
  HOST = 'HOST',
  BUSSER = 'BUSSER',
  DELIVERY_DRIVER = 'DELIVERY_DRIVER',
  STOCK_CLERK = 'STOCK_CLERK',
  OTHER = 'OTHER',
}
