export enum EventType {
  // Order Events
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',

  // Receipt Events
  RECEIPT_CREATED = 'RECEIPT_CREATED',
  RECEIPT_UPDATED = 'RECEIPT_UPDATED',
  RECEIPT_REFUNDED = 'RECEIPT_REFUNDED',

  // Table Events (Restaurant)
  TABLE_STATUS_CHANGED = 'TABLE_STATUS_CHANGED',
  TABLE_CREATED = 'TABLE_CREATED',
  TABLE_UPDATED = 'TABLE_UPDATED',
  TABLE_DELETED = 'TABLE_DELETED',

  // Menu Events
  MENU_ITEM_CREATED = 'MENU_ITEM_CREATED',
  MENU_ITEM_UPDATED = 'MENU_ITEM_UPDATED',
  MENU_ITEM_DELETED = 'MENU_ITEM_DELETED',
  PROMOTION_CREATED = 'PROMOTION_CREATED',
  PROMOTION_UPDATED = 'PROMOTION_UPDATED',
  PROMOTION_DELETED = 'PROMOTION_DELETED',

  // Employee Events
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  EMPLOYEE_DELETED = 'EMPLOYEE_DELETED',

  // Entity/Branch Events
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  BRANCH_DELETED = 'BRANCH_DELETED',

  // Pump Events (Gas Station)
  PUMP_CREATED = 'PUMP_CREATED',
  PUMP_UPDATED = 'PUMP_UPDATED',
  PUMP_STATUS_CHANGED = 'PUMP_STATUS_CHANGED',
  PUMP_DELETED = 'PUMP_DELETED',
}
